package main

import (
	"context"
	"encoding/csv"
	"encoding/json"
	"errors"
	"io"
	"net/http"
	"os"
	"path/filepath"
	"reflect"
	"strings"
	"sync"
	"sync/atomic"
	"testing"
	"time"

	"github.com/Azure/azure-sdk-for-go/sdk/azcore"
	"github.com/Azure/azure-sdk-for-go/sdk/azcore/policy"
	"github.com/DeBoX85/Cloud-Assess/internal/arg"
	"github.com/DeBoX85/Cloud-Assess/internal/assessment"
	"github.com/DeBoX85/Cloud-Assess/internal/azure"
	"github.com/DeBoX85/Cloud-Assess/internal/branding"
	"github.com/DeBoX85/Cloud-Assess/internal/config"
	"github.com/DeBoX85/Cloud-Assess/internal/discovery"
	"github.com/DeBoX85/Cloud-Assess/internal/orchestration"
	"github.com/DeBoX85/Cloud-Assess/internal/plugins/aigov"
	"github.com/DeBoX85/Cloud-Assess/internal/plugins/carbon"
	"github.com/DeBoX85/Cloud-Assess/internal/plugins/servicehealth"
	"github.com/DeBoX85/Cloud-Assess/internal/plugins/sqleol"
	"github.com/DeBoX85/Cloud-Assess/internal/plugins/zone"
	"github.com/DeBoX85/Cloud-Assess/internal/result"
	"github.com/DeBoX85/Cloud-Assess/internal/rules"
	"github.com/xuri/excelize/v2"
)

const cliAIID = "/subscriptions/" + cliZoneSub + "/resourceGroups/fixture-rg/providers/Microsoft.CognitiveServices/accounts/fixture-ai"
const cliAIQuery = `resources
| where type =~ "Microsoft.CognitiveServices/accounts"
| where isempty(kind) or kind contains "openai" or kind contains "aiservices"
| project id, subscriptionId, resourceGroup, location, type, name, sku.name, sku.tier, kind
| order by subscriptionId, resourceGroup`
const cliAIRow = `{"id":"` + cliAIID + `","subscriptionId":"` + cliZoneSub + `","resourceGroup":"fixture-rg","name":"fixture-ai","location":"westeurope","type":"Microsoft.CognitiveServices/accounts","kind":"OpenAI","sku_name":"S0","sku_tier":"irrelevant-tier"}`

type cliAICredential struct {
	t      *testing.T
	mu     sync.Mutex
	scopes map[string]int
}

func (c *cliAICredential) GetToken(ctx context.Context, o policy.TokenRequestOptions) (azcore.AccessToken, error) {
	if len(o.Scopes) != 1 || o.Scopes[0] != "https://management.core.windows.net/.default" && o.Scopes[0] != "https://metrics.monitor.azure.com/.default" {
		c.t.Error("AI separate production audiences")
	}
	c.mu.Lock()
	c.scopes[o.Scopes[0]]++
	c.mu.Unlock()
	return azcore.AccessToken{Token: "synthetic-ai-canary", ExpiresOn: time.Now().Add(time.Hour)}, ctx.Err()
}

type cliAIBody struct {
	io.Reader
	closed *atomic.Int32
}

func (b cliAIBody) Close() error { b.closed.Add(1); return nil }

func aiCommandOperations(t *testing.T) orchestration.Operations {
	t.Helper()
	ops := orchestration.Operations{}
	v := reflect.ValueOf(&ops).Elem()
	typ := v.Type()
	for i := 0; i < v.NumField(); i++ {
		name := typ.Field(i).Name
		f := v.Field(i)
		f.Set(reflect.MakeFunc(f.Type(), func([]reflect.Value) []reflect.Value { t.Fatalf("unexpected AI operation %s", name); return nil }))
	}
	return ops
}

// The real Cobra executor/factories/coordinator/renderers consume authenticated
// in-memory responses. Expected metadata and all16 cells are independent pinned
// source captures, not values generated by the target projection/decoder.
func TestAICobraAuthenticatedFactoriesReportsSourceCells(t *testing.T) {
	for _, key := range []string{azure.EnvAzureCloud, azure.EnvAzureAuthorityHost, azure.EnvAzureResourceManagerEndpoint, azure.EnvAzureResourceManagerAudience} {
		t.Setenv(key, "")
	}
	modes := []string{"only", "mixed", "scanner-aif", "scanner-vm", "empty", "no-metrics", "discovery-warning", "discovery-denied", "discovery-malformed", "discovery-late", "discovery-late-malformed", "metrics-denied", "metrics-malformed", "deployment-denied", "deployment-malformed", "cancel-discovery", "cancel-enrichment", "unknown-include", "exclude-only", "known-include", "known-exclude", "exclude-resource", "scope-critical", "all", "all-partial", "all-cancel", "formula", "output-failure", "stdout-failure"}
	for _, mode := range modes {
		for _, masked := range []bool{false, true} {
			t.Run(mode+map[bool]string{false: "-raw", true: "-masked"}[masked], func(t *testing.T) {
				capture := "source-all.json"
				if mode == "deployment-denied" || mode == "deployment-malformed" {
					capture = "source-deployment-denied.json"
				}
				data, err := os.ReadFile("../../internal/plugins/aigov/testdata/" + capture)
				if err != nil {
					t.Fatal(err)
				}
				var source []struct {
					Metadata    assessment.PluginMetadata
					SheetName   string `json:"sheet_name"`
					Description string
					Table       [][]string
				}
				// Source Type is an integer; decode only the original string metadata.
				var wire []struct {
					Metadata    struct{ Name, Version, Description, Author, License string }
					SheetName   string `json:"sheet_name"`
					Description string
					Table       [][]string
				}
				if json.Unmarshal(data, &wire) != nil || len(wire) != 1 {
					t.Fatal("AI source capture")
				}
				m := wire[0].Metadata
				source = append(source, struct {
					Metadata    assessment.PluginMetadata
					SheetName   string `json:"sheet_name"`
					Description string
					Table       [][]string
				}{assessment.PluginMetadata{Name: m.Name, Version: m.Version, Description: m.Description, Author: m.Author, License: m.License, Type: "internal"}, wire[0].SheetName, wire[0].Description, wire[0].Table})
				expected := wire[0].Table
				empty := mode == "empty" || mode == "no-metrics" || mode == "scanner-vm" || mode == "discovery-denied" || mode == "discovery-malformed" || mode == "metrics-denied" || mode == "metrics-malformed" || mode == "cancel-discovery" || mode == "cancel-enrichment" || mode == "unknown-include" || mode == "known-exclude" || mode == "exclude-resource" || mode == "scope-critical" || mode == "all-cancel"
				if empty {
					expected = expected[:1]
				}
				if mode == "formula" {
					for _, row := range expected[1:] {
						if row[6] == "fixture-model" {
							row[6] = "=SUM(1,1)"
						}
					}
				}
				ctx, cancel := context.WithCancel(context.Background())
				defer cancel()
				base := filepath.Join(t.TempDir(), "ai")
				var requests, closed, graphCalls, metricCalls, deploymentCalls atomic.Int32
				cred := &cliAICredential{t: t, scopes: map[string]int{}}
				metrics, err := os.ReadFile("../../internal/plugins/aigov/testdata/metrics-input.json")
				if err != nil {
					t.Fatal(err)
				}
				deployments, err := os.ReadFile("../../internal/plugins/aigov/testdata/deployments-input.json")
				if err != nil {
					t.Fatal(err)
				}
				client := func(scope string) *azure.HTTPClient {
					opts := azure.DefaultHTTPClientOptions(time.Second)
					opts.Scope = scope
					opts.MaxRetries = -1
					opts.Transport = cliZoneTransport(func(r *http.Request) (*http.Response, error) {
						requests.Add(1)
						if r.Header.Get("Authorization") != "Bearer synthetic-ai-canary" {
							t.Error("AI auth missing")
						}
						deadline, ok := r.Context().Deadline()
						if !ok || time.Until(deadline) > aigov.MaxDuration {
							t.Error("enclosing AI lifecycle absent")
						}
						body := ""
						status := 200
						switch r.URL.Host {
						case "management.azure.com":
							if strings.Contains(r.URL.Path, "Microsoft.ResourceGraph") {
								n := graphCalls.Add(1)
								if scope != "https://management.core.windows.net/.default" || r.Method != "POST" || r.URL.String() != "https://management.azure.com/providers/Microsoft.ResourceGraph/resources?api-version=2024-04-01" {
									t.Error("AI Graph confinement")
								}
								var request map[string]any
								if json.NewDecoder(r.Body).Decode(&request) != nil {
									t.Fatal("AI Graph body")
								}
								options := map[string]any{"$top": float64(1000), "resultFormat": "objectArray"}
								if n == 2 {
									options["$skipToken"] = "https://private-token.invalid/canary"
								}
								want := map[string]any{"subscriptions": []any{cliZoneSub}, "query": cliAIQuery, "options": options}
								if !reflect.DeepEqual(request, want) {
									t.Error("AI source Graph query/scope/token")
								}
								body = `{"count":1,"totalRecords":1,"resultTruncated":"false","data":[` + cliAIRow + `]}`
								if mode == "empty" {
									body = `{"count":0,"totalRecords":0,"resultTruncated":"false","data":[]}`
								}
								if mode == "discovery-warning" {
									body = `{"count":2,"totalRecords":2,"resultTruncated":"false","data":[` + cliAIRow + `,{}]}`
								}
								if mode == "discovery-denied" {
									status = 403
								}
								if mode == "discovery-malformed" {
									body = `{"count":1}`
								}
								if mode == "discovery-late" || mode == "discovery-late-malformed" || mode == "all-partial" {
									if n == 1 {
										body = `{"count":1,"totalRecords":2,"resultTruncated":"false","$skipToken":"https://private-token.invalid/canary","data":[` + cliAIRow + `]}`
									} else if mode == "discovery-late-malformed" {
										body = `{"count":0}`
									} else {
										status = 403
									}
								}
								if mode == "cancel-discovery" || mode == "all-cancel" {
									cancel()
									return nil, context.Canceled
								}
							} else {
								deploymentCalls.Add(1)
								if scope != "https://management.core.windows.net/.default" || r.Method != "GET" || r.URL.String() != "https://management.azure.com"+cliAIID+"/deployments?api-version=2025-06-01" || r.Body != nil {
									t.Error("AI deployment confinement")
								}
								body = string(deployments)
								if mode == "deployment-denied" {
									status = 403
								}
								if mode == "deployment-malformed" {
									body = `{"value":[{"name":"fixture-deployment","sku":{"capacity":-1}}]}`
								}
							}
						case "westeurope.metrics.monitor.azure.com":
							metricCalls.Add(1)
							q := r.URL.Query()
							want := map[string]string{"api-version": "2024-02-01", "metricnamespace": "Microsoft.CognitiveServices/accounts", "metricnames": "AzureOpenAIRequests", "aggregation": "Count", "interval": "PT1H", "filter": "StatusCode eq '*' and ModelDeploymentName eq '*' and ModelName eq '*'", "starttime": "2026-09-26T11:34:56Z", "endtime": "2026-10-03T10:34:56Z"}
							if scope != "https://metrics.monitor.azure.com/.default" || r.Method != "POST" || r.URL.Path != "/subscriptions/"+cliZoneSub+"/metrics:getBatch" || len(q) != len(want) {
								t.Error("AI Monitor confinement")
							}
							for k, v := range want {
								if q.Get(k) != v || len(q[k]) != 1 {
									t.Error("AI source metric options/window")
								}
							}
							var request map[string][]string
							if json.NewDecoder(r.Body).Decode(&request) != nil || !reflect.DeepEqual(request, map[string][]string{"resourceids": {cliAIID}}) {
								t.Error("AI metric account correlation")
							}
							body = string(metrics)
							if mode == "formula" {
								body = strings.ReplaceAll(body, "fixture-model", "=SUM(1,1)")
							}
							if mode == "no-metrics" {
								body = `{"values":[{"resourceid":"` + cliAIID + `","value":[]}]}`
							}
							if mode == "metrics-denied" {
								status = 403
							}
							if mode == "metrics-malformed" {
								body = `{"values":null}`
							}
							if mode == "cancel-enrichment" {
								cancel()
								return nil, context.Canceled
							}
						default:
							t.Fatal("AI authenticated destination escaped explicit in-memory transport")
						}
						if status != 200 {
							body = `{"error":{"message":"provider-private-canary"}}`
						}
						return &http.Response{StatusCode: status, Header: http.Header{}, Body: cliAIBody{strings.NewReader(body), &closed}, Request: r}, nil
					})
					return azure.NewHTTPClient(cred, opts)
				}
				arm := client("https://management.core.windows.net/.default")
				d, err := aigov.NewDiscoveryWithClient("https://management.azure.com", arm)
				if err != nil {
					t.Fatal(err)
				}
				s, err := aigov.NewWithClients("https://management.azure.com", client("https://metrics.monitor.azure.com/.default"), arm, func() time.Time { return time.Date(2026, 10, 3, 12, 34, 56, 987, time.FixedZone("fixture", 7200)) })
				if err != nil {
					t.Fatal(err)
				}
				execution, err := aigov.NewExecutionWithScanners(d, s)
				if err != nil {
					t.Fatal(err)
				}
				ops := aiCommandOperations(t)
				inventoryCalls := 0
				order := []string{}
				ops.DiscoverSubscriptions = func(_ context.Context, ids []string, _ *config.Filters) (map[string]string, error) {
					if !reflect.DeepEqual(ids, []string{cliZoneSub}) {
						t.Error("AI explicit selected scope")
					}
					if mode == "scope-critical" {
						return nil, errors.New("scope unavailable")
					}
					return map[string]string{cliZoneSub: "Synthetic subscription"}, nil
				}
				ops.ScanAIGovernance = func(c context.Context, subs map[string]string, f *config.AssessmentFilter) (assessment.PluginTable, error) {
					order = append(order, "ai-gov")
					return execution.Scan(c, subs, f)
				}
				all := strings.HasPrefix(mode, "all")
				regular := all || mode == "mixed" || strings.HasPrefix(mode, "scanner-") || strings.HasPrefix(mode, "known-")
				if regular {
					ops.DiscoverResources = func(_ context.Context, _ map[string]string, f *config.Filters) (*discovery.ResourceInventory, error) {
						inventoryCalls++
						f.Assessment.SetResourceScope(cliAIID, mode != "known-exclude")
						return &discovery.ResourceInventory{Included: []assessment.Resource{{ID: "/subscriptions/" + cliZoneSub + "/resourceGroups/other/providers/Microsoft.Compute/virtualMachines/healthy", SubscriptionID: cliZoneSub, ResourceGroup: "other", Type: "microsoft.compute/virtualmachines", Name: "healthy"}}}, nil
					}
					ops.LoadCatalog = func() (*rules.Catalog, error) { return rules.NewCatalog(), nil }
					ops.ExecuteGraph = func(context.Context, []assessment.RecommendationDefinition, map[string]string, *config.AssessmentFilter) ([]assessment.Finding, []arg.RuleWarning, error) {
						return nil, nil, nil
					}
				}
				if all {
					service := servicehealth.NewWithTransport(cliSQLGraph(func(context.Context, arg.Request) (*arg.Response, error) {
						return &arg.Response{Data: []json.RawMessage{json.RawMessage(`{"subscriptionId":"11111111-1111-4111-8111-111111111111","targetRegion":"westus","targetResourceType":"microsoft.compute/virtualmachines","percentageOfTimeWithoutEvents":100,"events":0,"affectedResources":0}`)}}, nil
					}))
					ops.ScanCarbon = func(context.Context, map[string]string, *config.AssessmentFilter) (assessment.PluginTable, error) {
						order = append(order, carbon.Name)
						v := carbon.PendingTable()
						v.Health = assessment.StageExecution{Name: carbon.Name, Status: assessment.StageCompleted}
						return v, nil
					}
					ops.ScanServiceHealth = func(c context.Context, s map[string]string, f *config.AssessmentFilter) (assessment.PluginTable, error) {
						order = append(order, servicehealth.Name)
						return service.Scan(c, s, f)
					}
					ops.ScanSQLEOL = func(context.Context, map[string]string, *config.AssessmentFilter) (assessment.PluginTable, error) {
						order = append(order, sqleol.Name)
						v := sqleol.PendingTable()
						v.Health = assessment.StageExecution{Name: sqleol.Name, Status: assessment.StageCompleted}
						return v, nil
					}
					ops.ScanZoneMapping = func(context.Context, map[string]string) (zone.Result, error) {
						order = append(order, "zone-mapping")
						return zone.Result{Rows: []zone.Row{{SubscriptionID: cliZoneSub, SubscriptionName: "Synthetic subscription", Location: "westus", DisplayName: "West US", LogicalZone: "1", PhysicalZone: "westus-az1"}}}, nil
					}
				}
				filterArgs := []string{}
				if mode == "unknown-include" || strings.HasPrefix(mode, "known-") || mode == "exclude-only" || mode == "exclude-resource" {
					text := "assessment:\n  include:\n    tags: {Environment: dev}\n"
					if mode == "exclude-only" {
						text = "assessment:\n  exclude:\n    tags: {Environment: prod}\n"
					}
					if mode == "exclude-resource" {
						text = "assessment:\n  exclude:\n    resources: ['" + cliAIID + "']\n"
					}
					path := filepath.Join(filepath.Dir(base), "filters.yaml")
					if os.WriteFile(path, []byte(text), 0600) != nil {
						t.Fatal("filter fixture")
					}
					filterArgs = []string{"--filters", path}
				}
				stdoutFile, err := os.Create(filepath.Join(filepath.Dir(base), "stdout.json"))
				if err != nil {
					t.Fatal(err)
				}
				previousStdout := os.Stdout
				os.Stdout = stdoutFile
				defer func() { os.Stdout = previousStdout; stdoutFile.Close() }()
				if mode == "stdout-failure" {
					stdoutFile.Close()
				}
				if mode == "output-failure" {
					if os.Mkdir(base+".xlsx", 0700) != nil || os.WriteFile(base+".json", []byte("previous report"), 0600) != nil {
						t.Fatal("retained output fixture")
					}
				}
				credentialCalls, factoryCalls := 0, 0
				root := newRootCommand(func(c context.Context, f scanFlags) (int, error) {
					return executeScanWithFactories(c, f, func() (azcore.TokenCredential, error) { credentialCalls++; return cred, nil }, func(azcore.TokenCredential) (orchestration.Operations, error) { factoryCalls++; return ops, nil })
				})
				root.SetContext(context.WithValue(ctx, exitCodeContextKey{}, root.Context().Value(exitCodeContextKey{})))
				args := []string{"ai-gov", "--subscription-id", cliZoneSub, "--json", "--csv", "--sarif", "--stdout", "--output-name", base}
				args = append(args, filterArgs...)
				if regular {
					args[0] = "scan"
					args = append(args, "--plugin", "ai-gov", "--stages=-diagnostics,-advisor,-defender")
				}
				if strings.HasPrefix(mode, "scanner-") {
					args = append([]string{args[0], strings.TrimPrefix(mode, "scanner-")}, args[1:]...)
				}
				if all {
					for i, arg := range args {
						if arg == "--plugin" {
							args[i+1] = "zone-mapping,sql-eol,carbon-emissions,service-health,ai-gov,ai-gov"
						}
					}
				}
				if !masked {
					args = append(args, "--redact-subscription-ids=false")
				}
				root.SetArgs(args)
				err = root.Execute()
				os.Stdout = previousStdout
				stdoutFile.Close()
				wantExit := 0
				switch mode {
				case "discovery-denied", "discovery-malformed", "discovery-late", "discovery-late-malformed", "metrics-denied", "metrics-malformed", "all-partial":
					wantExit = 3
				case "cancel-discovery", "cancel-enrichment", "scope-critical", "all-cancel", "output-failure", "stdout-failure":
					wantExit = 1
				}
				if *root.Context().Value(exitCodeContextKey{}).(*int) != wantExit || (err != nil) != (wantExit != 0) || credentialCalls != 1 || factoryCalls != 1 {
					if all {
						data, _ := os.ReadFile(base + ".json")
						var diagnostic result.AssessmentResult
						_ = json.Unmarshal(data, &diagnostic)
						for _, table := range diagnostic.PluginTables {
							t.Logf("%s health: %+v", table.Metadata.Name, table.Health)
						}
					}
					t.Fatalf("AI real factory artifact-before-exit: %d %v", *root.Context().Value(exitCodeContextKey{}).(*int), err)
				}
				if strings.HasPrefix(mode, "cancel-") || mode == "all-cancel" {
					if !errors.Is(err, context.Canceled) {
						t.Fatal("AI cancellation identity lost")
					}
				}
				if mode == "output-failure" {
					b, _ := os.ReadFile(base + ".json")
					if string(b) != "previous report" {
						t.Fatal("AI render failure replaced existing report")
					}
					return
				}
				b, err := os.ReadFile(base + ".json")
				if err != nil {
					t.Fatal(err)
				}
				if strings.Contains(string(b), "canary") || masked && strings.Contains(string(b), cliZoneSub) {
					t.Fatal("AI provider/credential/identity leakage")
				}
				var report result.AssessmentResult
				if json.Unmarshal(b, &report) != nil || report.SchemaVersion != "1.1" {
					t.Fatal("AI canonical schema")
				}
				count := 1
				if all {
					count = 5
				}
				if len(report.PluginTables) != count {
					t.Fatal("AI selected tables missing")
				}
				table := report.PluginTables[0]
				sheet := "AI Gov"
				if mode == "empty" || mode == "scanner-vm" || mode == "discovery-denied" || mode == "discovery-malformed" || mode == "cancel-discovery" || mode == "unknown-include" || mode == "known-exclude" || mode == "exclude-resource" || mode == "scope-critical" || mode == "all-cancel" {
					sheet = "AI Throttling"
				}
				if table.Metadata != source[0].Metadata || table.SheetName != sheet || table.Description != wire[0].Description || !reflect.DeepEqual(table.Columns, expected[0]) || len(table.Rows) != len(expected)-1 || table.Health.Records != len(expected)-1 {
					t.Fatalf("AI source metadata/branch/header: %+v", table)
				}
				for i, row := range table.Rows {
					wantID := cliZoneSub
					if masked {
						wantID = "xxxxxxxx-xxxx-xxxx-xxxx-xxxxx1111111"
					}
					if row.SubscriptionID != wantID || !reflect.DeepEqual(row.Cells, expected[i+1]) {
						t.Fatalf("AI all16 captured JSON cells: %+v", row)
					}
				}
				if regular && mode != "scope-critical" && (inventoryCalls != 1 || len(report.Resources) != 1 || report.Resources[0].Name != "healthy") {
					t.Fatal("AI failure discarded independent inventory")
				}
				if all {
					want := []string{"ai-gov", "carbon-emissions", "service-health", "sql-eol", "zone-mapping"}
					if mode == "all-cancel" {
						want = want[:1]
					}
					if !reflect.DeepEqual(order, want) {
						t.Fatal("AI alphabetical selection/dedup/cancellation")
					}
					if mode == "all-partial" && len(report.PluginTables[4].Rows) != 1 {
						t.Fatal("AI discovery failure discarded later plugin")
					}
					if mode == "all-cancel" {
						for _, v := range report.PluginTables[1:] {
							if v.Health.Status != assessment.StageSkipped {
								t.Fatal("AI cancellation lost pending requested headers")
							}
						}
					}
				}
				if mode == "discovery-late" || mode == "discovery-late-malformed" || mode == "all-partial" {
					if table.Health.Status != assessment.StageFailed || !strings.HasPrefix(table.Health.Error.Code, "ai_discovery_") {
						t.Fatal("enrichment concealed failed discovery")
					}
				}
				if mode == "scope-critical" && table.Health.Status != assessment.StageSkipped {
					t.Fatal("critical scope lost pending AI table")
				}
				if requests.Load() != closed.Load() && !(strings.HasPrefix(mode, "cancel-") || mode == "all-cancel") {
					t.Fatal("AI response body leak")
				}
				if mode == "scope-critical" && requests.Load() != 0 {
					t.Fatal("critical scope authenticated AI")
				}
				if len(expected) > 1 && (metricCalls.Load() != 1 || deploymentCalls.Load() != 1 || cred.scopes["https://metrics.monitor.azure.com/.default"] == 0 || cred.scopes["https://management.core.windows.net/.default"] == 0) {
					t.Fatal("AI authenticated source pipeline not executed")
				}
				if mode != "stdout-failure" {
					std, _ := os.ReadFile(filepath.Join(filepath.Dir(base), "stdout.json"))
					var out result.AssessmentResult
					if json.Unmarshal(std, &out) != nil || !reflect.DeepEqual(out.PluginTables, report.PluginTables) || masked && strings.Contains(string(std), cliZoneSub) {
						t.Fatal("AI canonical stdout/masking")
					}
				}
				f, err := os.Open(base + ".plugin_ai-gov_requests.csv")
				if err != nil {
					t.Fatal(err)
				}
				cells, err := csv.NewReader(f).ReadAll()
				f.Close()
				if err != nil {
					t.Fatal(err)
				}
				csvExpected := make([][]string, len(expected))
				for i, row := range expected {
					csvExpected[i] = append([]string(nil), row...)
					for j, cell := range csvExpected[i] {
						if strings.HasPrefix(cell, "=") {
							csvExpected[i][j] = "'" + cell
						}
					}
				}
				if !reflect.DeepEqual(cells, csvExpected) {
					t.Fatalf("AI every CSV cell: %+v", cells)
				}
				book, err := excelize.OpenFile(base + ".xlsx")
				if err != nil {
					t.Fatal(err)
				}
				xls, err := book.GetRows(sheet)
				if err != nil || len(xls) < 4 || !reflect.DeepEqual(xls[0], []string{branding.Default().ReportTitle}) || !reflect.DeepEqual(xls[3:], expected) {
					t.Fatalf("AI every XLSX cell: %+v %v", xls, err)
				}
				if mode == "formula" {
					cellType, e := book.GetCellType(sheet, "G6")
					formula, e2 := book.GetCellFormula(sheet, "G6")
					if e != nil || e2 != nil || formula != "" || cellType != excelize.CellTypeSharedString && cellType != excelize.CellTypeInlineString {
						t.Fatal("AI untrusted formula model is not text")
					}
				}
				book.Close()
				sarif, err := os.ReadFile(base + ".sarif")
				if err != nil || strings.Contains(string(sarif), "Request Count") || strings.Contains(string(sarif), "plugin_ai-gov") {
					t.Fatal("AI table invented SARIF findings")
				}
			})
		}
	}
}
