package main

import (
	"bytes"
	"context"
	"errors"
	"os"
	"strings"
	"testing"

	"github.com/DeBoX85/Cloud-Assess/internal/rules"
)

func TestRulesJSONMatchesPinnedReferenceExecutable(t *testing.T) {
	// Captured by the untouched pinned AZQR rules --json executable with the
	// pinned APRL submodule, not generated by the target selection function.
	want, err := os.ReadFile("testdata/rules-reference.json")
	if err != nil {
		t.Fatal(err)
	}
	for _, flag := range []string{"--json", "-j", "--json=true"} {
		t.Run(flag, func(t *testing.T) {
			root := newRootCommand(func(context.Context, scanFlags) (int, error) {
				t.Fatal("rules inspection called the scan executor")
				return 1, nil
			})
			var output bytes.Buffer
			root.SetOut(&output)
			root.SetArgs([]string{"rules", flag})
			if err := root.Execute(); err != nil {
				t.Fatal(err)
			}
			if !bytes.Equal(output.Bytes(), want) {
				t.Fatal("rules JSON differs from independently captured pinned reference output")
			}
		})
	}
}

func TestRulesMarkdownAndInvalidArguments(t *testing.T) {
	root := newRootCommand(func(context.Context, scanFlags) (int, error) {
		t.Fatal("offline command called scan executor")
		return 1, nil
	})
	var output bytes.Buffer
	root.SetOut(&output)
	root.SetArgs([]string{"rules"})
	if err := root.Execute(); err != nil {
		t.Fatal(err)
	}
	text := output.String()
	if !strings.HasPrefix(text, "## Recommendations List\n\nTotal Supported Azure Resource Types: 107\n") || strings.Count(text, "\n| ") != 382 {
		t.Fatal("unexpected pinned Markdown heading/table row count")
	}
	for _, args := range [][]string{{"rules", "extra"}, {"rules", "--subscription-id", "unused"}, {"rules", "--json=invalid"}} {
		root := newRootCommand(func(context.Context, scanFlags) (int, error) {
			t.Fatal("invalid offline command called scan executor")
			return 1, nil
		})
		root.SetArgs(args)
		if err := root.Execute(); err == nil {
			t.Fatalf("accepted invalid rules args: %v", args)
		}
	}
}

type failedRulesWriter struct{ err error }

func (w failedRulesWriter) Write([]byte) (int, error) { return 0, w.err }

func TestRulesOutputFailuresAndMarkdownEscaping(t *testing.T) {
	failure := errors.New("synthetic output failure")
	for _, jsonOutput := range []bool{false, true} {
		if err := writeRules(failedRulesWriter{failure}, []rules.InspectionRow{}, 0, jsonOutput); !errors.Is(err, failure) {
			t.Fatalf("output failure lost: %v", err)
		}
	}
	var output bytes.Buffer
	rows := []rules.InspectionRow{{RecommendationID: "one", Recommendation: "<script>& | a\r\nb\nc", LearnMoreURL: "https://example.test/a)|b"}}
	if err := writeRules(&output, rows, 1, false); err != nil {
		t.Fatal(err)
	}
	text := output.String()
	if strings.Contains(text, "<script>") || !strings.Contains(text, "&lt;script&gt;&amp; &#124; a<br>b<br>c") || !strings.Contains(text, "https://example.test/a)&#124;b") || strings.Count(text, "\n| ") != 3 {
		t.Fatal("untrusted cell text changed Markdown table structure")
	}
}
